[package]
name = "next_semver"
version = "0.1.0"
edition = "2021"

[lib]
name = "next_semver"
path = "src/lib.rs"

[[bin]]
name = "next_semver"
path = "src/main.rs"
required-features = ["web"]

[features]
web = ["rocket"]

[dependencies]
rocket = { version = "0.5.0-rc.1", optional = true }

