
{{ if not .Values.prod }}

#TODO @mark: turn this into some reusable service

{{ $self := printf "timebomb-ns-%s" .Release.Namespace | trunc 63 | lower }}
{{ $currentDate := now | dateModify "+72h" | date "2006-01-02" }}
{{ $currentDay := int (substr 8 10 $currentDate) }}
{{ $cleanupDay := mod (add $currentDay 3) 29 }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $self | quote }}
  namespace: cleaners
  labels:
    start_day: {{ $currentDay | quote }}
    clean_day: {{ $cleanupDay | quote }}
spec:
  schedule: "0 3 {{ $cleanupDay }} * *"
  jobTemplate:
    spec:
      template:
        spec:
          # this account needs to be created
          serviceAccountName: cleanup-account
          restartPolicy: Never
          containers:
            - name: {{ $self | quote }}
              image: mverleg/ns-timebomb:latest
              args:
                - {{ .Release.Namespace | quote }}
                - {{ $self | quote }}
              resources:
                requests:
                  memory: "32Mi"
                  cpu: "100m"
                limits:
                  memory: "64Mi"
                  cpu: "100m"
{{ end }}
