
{{ if not .Values.prod }}

apiVersion: batch/v1
kind: Job
metadata:
  name: timebomb-ns-{{ .Release.Namespace }}
  namespace: cleaners
spec:
  template:
    spec:
      # this account needs to be created once
      serviceAccountName: cleanup-account
      restartPolicy: Never
      containers:
        - name: timebomb-ns-{{ .Release.Namespace }}
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              for i in {1..72}
              do
                  echo "$(date): hour $i until deletion of namespace {{ .Release.Namespace }}"
                  sleep 3600
              done
              echo "Deleting namespace {{ .Release.Namespace }} NOW";
              kubectl delete namespace {{ .Release.Namespace }};
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "100m"
{{ end }}
