
apiVersion: apps/v1
kind: Deployment
namespace: {{ .Release.Namespace }}
# This describes the actual deployment:
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    # This describes what pods to create:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
          - name: {{ .Release.Name }}-pod
            image: "mverleg/next_semver:{{ .Values.image_tag }}"
            imagePullPolicy: Always
  # This describes which pods are part of the deployment,
  # so this should match 'metadata' in almost all cases:
  selector:
    matchLabels:
      app: {{ .Release.Name }}

