
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-service
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/hsts: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/server-alias: "*.{{ .Values.domain }}"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.domain }}
        - www.{{ .Values.domain }}
      secretName: next-tryin-top-tls
  rules:
      - host: {{ .Values.domain }}
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: {{ .Release.Name }}-service
                  port:
                    number: 80
