
{{- if eq .Release.Namespace "default" }}
  {{- fail "cannot deploy into 'default' namespace" }}
{{- end }}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  namespace: ""
