
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    # port of pod to contact
    - targetPort: 8080
      # within the cluster (ClusterIP is inside-only)
      port: 80
  selector:
    app: {{ .Release.Name }}
