
apiVersion: v1
kind: Service
metadata:
  name: next-semver-service
  labels:
    app: next-semver
spec:
  type: ClusterIP
  ports:
    # port of pod to contact
    - targetPort: 8080
      # within the cluster (ClusterIP is inside-only)
      port: 8080
  selector:
    app: next-semver
